menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/zt515
    Links: /links/
    Rss: /atom.xml

favicon: https://raw.githubusercontent.com/zt515/Blog/master/themes/apollo/source/logo.png
logo: https://raw.githubusercontent.com/zt515/Blog/master/themes/apollo/source/logo.png

language: zh-cn

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016
