author: yanm1ng # 作者
description: Kiva's Blog
keyword: hexo-theme, vuejs
favicon: https://coding.net/u/Kiva/p/Kiva.coding.me/git/raw/master/css/images/logo.png

excerpt_link: 阅读全文

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 Mirror: http://mirror.imkiva.com
 About: /about/

# highlight
highlight:
  github

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

comment: gitalk

# gitalk config
gitalk_owner: imkiva
gitalk_repo: Blog
gitalk_oauth_id: c65c479a3282ef71e914
gitalk_oauth_secret: 0b9dc1194aa76d0ef3bb3eeae3d8cd8f0d766b41

baidu_id: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://coding.net/u/Kiva/p/Kiva.coding.me/git/raw/master/css/images/logo.png
  description: "Talk is cheap, show me the code."
  github_username: imkiva
  weibo_username: NNRRK
  zhihu_username: kiva-76

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
  #cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=default
